language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - DB=mysql

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_script:
  - sudo apt-get install parallel
  - composer self-update
  - cd ..
  - cp enetcache/composer.json .
  - composer --dev install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv enetcache typo3conf/ext

script:
  - >
    echo "Running unit tests";
    ./bin/phpunit --colors -c typo3conf/ext/enetcache/Build/UnitTests.xml
  - >
    echo "Running php lint";
    find typo3conf/ext/enetcache/ -name \*.php -exec php -l {} >/dev/null \;
