language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install

script:
  - >
    echo "Running unit tests";
    TYPO3_PATH_WEB=$PWD/.Build/Web .Build/bin/phpunit -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Tests/Unit/

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" -exec php -l {} >/dev/null \;
