language: php

php:
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install

script:
  - >
    cd .Build;
    echo "Running unit tests";
    TYPO3_PATH_WEB=$PWD/Web bin/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml Web/typo3conf/ext/enetcache/Tests/Unit/

  - >
    cd .Build/Web/typo3conf/ext/enetcache;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" -exec php -l {} >/dev/null \;
