language: php

php:
  - 7.2

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install

script:
  - >
    echo "Running unit tests";
    Build/Scripts/runTests.sh -s unit
    # TYPO3_PATH_WEB=$PWD/Web .Build/bin/phpunit -c .Build/vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml .Build/Web/typo3conf/ext/enetcache/Tests/Unit/

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" -exec php -l {} >/dev/null \;
