language: php

php:
  - 7.2
  - 7.3

sudo: true

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_install:
  - composer self-update
  - composer --version

before_script:
  - Build/Scripts/runTests.sh -s composerInstall

script:
  - >
    echo "Running unit tests";
    Build/Scripts/runTests.sh -s unit

  - >
    echo "Running php lint";
    Build/Scripts/runTests.sh -s lint
