language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    recipients:
      - lolli@schwarzbu.ch
    on_success: change
    on_failure: change

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer install
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - >
    echo "Running unit tests";
    .Build/bin/phpunit -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/

  - >
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" -exec php -l {} >/dev/null \;
