<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-11-11 18:03

$extensionPath = t3lib_extMgm::extPath('enetcache');
return array(
	'tx_enetcache' => $extensionPath . 'classes/class.tx_enetcache.php',
	'tx_enetcache_hook' => $extensionPath . 'classes/class.tx_enetcache_hook.php',
	'tx_enetcache_tcahandler' => $extensionPath . 'classes/class.tx_enetcache_tcaHandler.php',
	'tx_enetcache_cache_backend_compresseddbbackend' => $extensionPath . 'classes/class.tx_enetcache_cache_backend_compresseddbbackend.php',
	'tx_enetcache_backendcontentcacheaction' => $extensionPath . 'hooks/class.tx_enetcache_backendContentCacheAction.php',
	'tx_enetcache_tcemain' => $extensionPath . 'hooks/class.tx_enetcache_tcemain.php',
	'tx_enetcache_hookable' => $extensionPath . 'interfaces/interface.tx_enetcache_hookable.php',
	'tx_enetcache_testcase' => $extensionPath . 'tests/class.tx_enetcache_testcase.php',
	'tx_enetcache_gccachebackends' => $extensionPath . 'tasks/class.tx_enetcache_gccachebackends.php',
	'tx_enetcache_gccachebackends_additionalfieldprovider' => $extensionPath . 'tasks/class.tx_enetcache_gccachebackends_additionalfieldprovider.php',
);
?>
